### ISSUE TITLE
typo3 version 7.5 missing field label in settings form

### ISSUE THREAD

**Issue by lmaylein** [subugoe/typo3-xmlinclude#4]
No field labels for baseURL and startURL

![typo3_xmlinclude_settings](https://cloud.githubusercontent.com/assets/7468155/10790529/23ba2492-7d84-11e5-9a5b-ea237e854153.png)

**Comment by ipf** [comment]
![bildschirmfoto vom 2015-11-05 15-05-40](https://cloud.githubusercontent.com/assets/557076/10970443/e23fd3da-83ce-11e5-9784-6669812d8528.png)

Here an example. Maybe you need to clear the language cache on your typo3 instance that the label gets visible.
